/**
 * GitHub Actions workflow template for Frontguard.
 *
 * Generated by `frontguard init --ci`. The workflow runs Frontguard on every
 * pull request: checkout → setup node → install deps → install Playwright
 * browsers (cached) → start dev server → run frontguard → post PR comment.
 *
 * @module templates/github-actions
 */

import { CLI_VERSION } from '../version.js';

/** Package managers supported by the generated workflow. */
export type PackageManager = 'npm' | 'pnpm' | 'yarn' | 'bun';

/** Options for {@link generateGitHubActionsWorkflow}. */
export interface GitHubActionsOptions {
  /** Dev-server command to run before testing (e.g. `npm run dev`). */
  devCommand?: string;
  /** Existing package.json script that starts the dev server. */
  devScript?: string;
  /** Project package manager, detected from its lockfile. */
  packageManager?: PackageManager;
  /** Lockfile used to make installs and the browser cache deterministic. */
  lockfile?: string;
  /** Port the dev server listens on. */
  port?: number;
  /** Node.js version to use. */
  nodeVersion?: string;
}

/**
 * Generates the YAML contents for `.github/workflows/frontguard.yml`.
 *
 * The workflow is self-contained, requires no Docker, caches Playwright
 * browsers, and posts results to the PR via the built-in `github-pr` reporter
 * (which reads `GITHUB_TOKEN`).
 */
export function generateGitHubActionsWorkflow(options: GitHubActionsOptions = {}): string {
  const packageManager = options.packageManager ?? 'npm';
  const packageManagerConfig: Record<
    PackageManager,
    { installCommand: string; defaultLockfile: string }
  > = {
    npm: { installCommand: 'npm ci', defaultLockfile: 'package-lock.json' },
    pnpm: {
      installCommand: 'pnpm install --frozen-lockfile',
      defaultLockfile: 'pnpm-lock.yaml',
    },
    yarn: {
      installCommand: 'yarn install --frozen-lockfile',
      defaultLockfile: 'yarn.lock',
    },
    bun: {
      installCommand: 'bun install --frozen-lockfile',
      defaultLockfile: 'bun.lock',
    },
  };
  const managerConfig = packageManagerConfig[packageManager];
  const {
    port = 3000,
    nodeVersion = '20',
  } = options;
  const devCommand =
    options.devCommand ?? `${packageManager} run ${options.devScript ?? 'dev'}`;
  const lockfile = options.lockfile ?? managerConfig.defaultLockfile;
  const nodeCache = packageManager === 'npm' ? "\n          cache: 'npm'" : '';
  const packageManagerSetup =
    packageManager === 'pnpm' || packageManager === 'yarn'
      ? `      - name: Enable Corepack
        run: corepack enable ${packageManager}`
      : packageManager === 'bun'
        ? `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2`
        : '';

  return `# Frontguard visual regression testing
# Generated by \`frontguard init --ci\`. Edit to fit your project.
name: Frontguard

on:
  pull_request:
    branches: [main, master]

# This comparison workflow reads baselines and comments on PRs; it never updates baselines.
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: frontguard-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Full history so the baseline orphan branch can be fetched.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '${nodeVersion}'${nodeCache}

${packageManagerSetup}

      - name: Install dependencies
        run: ${managerConfig.installCommand}

      - name: Cache Playwright browsers
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: \${{ runner.os }}-playwright-frontguard-${CLI_VERSION}-\${{ hashFiles('**/${lockfile}') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npm exec --yes --package="@frontguard/cli@${CLI_VERSION}" -- playwright install --with-deps chromium firefox webkit

      - name: Start dev server
        run: |
          ${devCommand} &
          npx wait-on http://localhost:${port} --timeout 60000

      - name: Run Frontguard
        id: frontguard
        shell: bash
        run: |
          set -uo pipefail
          set +e
          npm exec --yes --package="@frontguard/cli@${CLI_VERSION}" -- frontguard run --url http://localhost:${port} --output json > /tmp/frontguard-result.json 2>/tmp/frontguard-stderr.log
          RUN_EXIT=$?
          set -e

          if [ -s /tmp/frontguard-stderr.log ]; then
            cat /tmp/frontguard-stderr.log >&2
          fi
          if ! REPORT_PATH=$(jq -er '.config.outputDir | select(type == "string" and length > 0)' /tmp/frontguard-result.json); then
            cat /tmp/frontguard-result.json
            echo "Frontguard did not return a report directory" >&2
            if [ "$RUN_EXIT" -eq 0 ]; then RUN_EXIT=2; fi
            exit "$RUN_EXIT"
          fi

          WORKSPACE_ROOT=$(node -e 'const fs=require("node:fs"),p=require("node:path");console.log(fs.realpathSync(p.resolve(process.argv[1])))' "$GITHUB_WORKSPACE")
          REPORT_ROOT=$(node -e 'const fs=require("node:fs"),p=require("node:path");console.log(fs.realpathSync(p.resolve(process.argv[1])))' "$REPORT_PATH")
          case "$REPORT_ROOT" in
            "$WORKSPACE_ROOT"|"$WORKSPACE_ROOT"/*) ;;
            *)
              echo "Refusing to upload report directory outside GITHUB_WORKSPACE: $REPORT_PATH" >&2
              exit 2
              ;;
          esac

          DELIM="ghadelim_$(openssl rand -hex 8)"
          {
            printf 'report-path<<%s\\n' "$DELIM"
            printf '%s\\n' "$REPORT_PATH"
            printf '%s\\n' "$DELIM"
          } >> "$GITHUB_OUTPUT"
          cat /tmp/frontguard-result.json
          exit "$RUN_EXIT"
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # Optional — enable AI classification by adding these secrets:
          # FRONTGUARD_OPENAI_KEY: \${{ secrets.FRONTGUARD_OPENAI_KEY }}
          # FRONTGUARD_ANTHROPIC_KEY: \${{ secrets.FRONTGUARD_ANTHROPIC_KEY }}

      - name: Upload Frontguard report (GitHub.com)
        if: always() && github.server_url == 'https://github.com' && steps.frontguard.outputs.report-path != ''
        uses: actions/upload-artifact@v7
        with:
          name: frontguard-report
          path: \${{ steps.frontguard.outputs.report-path }}
          if-no-files-found: error

      - name: Upload Frontguard report (GitHub Enterprise Server)
        if: always() && github.server_url != 'https://github.com' && steps.frontguard.outputs.report-path != ''
        uses: actions/upload-artifact@v3.2.2-node20
        with:
          name: frontguard-report
          path: \${{ steps.frontguard.outputs.report-path }}
          if-no-files-found: error
`;
}
