/**
 * GitHub Actions workflow template for Frontguard.
 *
 * Generated by `frontguard init --ci`. The workflow runs Frontguard on every
 * pull request: checkout → setup node → install deps → install Playwright
 * browsers (cached) → start dev server → run frontguard → post PR comment.
 *
 * @module templates/github-actions
 */

/** Options for {@link generateGitHubActionsWorkflow}. */
export interface GitHubActionsOptions {
  /** Dev-server command to run before testing (e.g. `npm run dev`). */
  devCommand?: string;
  /** Port the dev server listens on. */
  port?: number;
  /** Node.js version to use. */
  nodeVersion?: string;
}

/**
 * Generates the YAML contents for `.github/workflows/frontguard.yml`.
 *
 * The workflow is self-contained, requires no Docker, caches Playwright
 * browsers, and posts results to the PR via the built-in `github-pr` reporter
 * (which reads `GITHUB_TOKEN`).
 */
export function generateGitHubActionsWorkflow(options: GitHubActionsOptions = {}): string {
  const {
    devCommand = 'npm run dev',
    port = 3000,
    nodeVersion = '20',
  } = options;

  return `# Frontguard visual regression testing
# Generated by \`frontguard init --ci\`. Edit to fit your project.
name: Frontguard

on:
  pull_request:
    branches: [main, master]

# Allow the workflow to comment on PRs and push baseline commits.
permissions:
  contents: write
  pull-requests: write

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Full history so the baseline orphan branch can be fetched.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: \${{ runner.os }}-playwright-\${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Start dev server
        run: |
          ${devCommand} &
          npx wait-on http://localhost:${port} --timeout 60000

      - name: Run Frontguard
        run: npx frontguard run --url http://localhost:${port} --output json
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # Optional — enable AI classification by adding these secrets:
          # FRONTGUARD_OPENAI_KEY: \${{ secrets.FRONTGUARD_OPENAI_KEY }}
          # FRONTGUARD_ANTHROPIC_KEY: \${{ secrets.FRONTGUARD_ANTHROPIC_KEY }}
`;
}
